### ISSUE TITLE
Why does this project not receive more attention?

### ISSUE THREAD

**Issue by larsrinn** [drf-forms/drf-schema-adapter#23]
The repetitiveness of writing frontend and backend model definitions has always held me back from adding modern frontend application to my Django projects. I was looking for quite a while for a project like this and can't believe there isn't a massive amount of people in a similar situation. So I would have expected this project getting much more attention.

I know there is for example `django-angular` but that's only AngularJS and it doesn't seem to be easily ported to a modern version of Angular. Without having really tried either of the projects, I've got the feeling that `django-angular` brings too much own code to the frontend part of the application and hence limiting the frontend developers options to stick to well established patterns. In my impression `drf-schema-adapter` is positioned just right by only defining "base `models` and `services`". Also I like that it is more generic concerning the frontend framework.

So I wondered why there aren't many more users, which made my kind of skeptical. Is there any drawback I didn't recognize? Or are there more popular, similar projects that have kept under my radar? Please don't get that wrong, what I've seen looks fantastic. I'll be happy to assist in making the project more popular. What do you think would be required most urgently?

**Comment by adrienbrunet** [comment]
@nanuxbe will answer it better but I think she used it a lot for her own projects and work but mainly with ember. I tried to help with the angular (1) part. I was/am a maintainer of Django-angular and I really like the new approach @nanuxbe proposed. It has a lot more potential. I spoke with some drf people and they liked the idea to exploit more the option call.

I've stopped using angular and started using vuejs but I did not get time to work on this and did not get the chance to use it within my projects. You should give it a try. On what js framework are you working ?

**Comment by larsrinn** [comment]
We have not decided which frontend framework to use but Vue currently looks like our favorite. What do you do in order to keep your frontend DRY? I would be very much interested in how to integrate Django and Vue best. And maybe we could work on a Vue adapter?

**Comment by nanuxbe** [comment]
Hi @larsrinn ,

I'm not sure why this project isn't getting more attention, I'm trying to talk about it every chance I get ;-)
Indeed, a lot of people struggle with the same problem of writing models for backend + frontend and this is how this project came to life, by bringing together people who had all tried to solve this problem each on their own.

As @adrienbrunet said, I use this project a lot (daily) and, working fullstack, I don't see any drawbacks.
Some projects with separate frontend and backend team might see drawbacks in the fact frontend and backend _need_ to evolve in sync.

I use it mainly with Ember and have used it some with Angular2, I believe it should still work as-is with Angular5 but I haven't had the chance to try it yet.
If you have the time and energy, a Vue adapter would be very welcome. I have never tried Vue but maybe it can work with the MobX+Axios adapter (that was designed for React) since I don't think (and I may be totally wrong) Vue has its own data layer.

As far as drawbacks are concerned, I might as well mention that the user documentation is a bit lagging behind and the developer documentation is quite non-existent. I'm planning to sprint on that Djangocon Europe though.

If you decide to write your own adapter and have any questions, feel free to reach out!

**Comment by adrienbrunet** [comment]
I'm currently off in Australia for a period of 3months. I won't be able to contribute during this period but I'd love to help you with a Vue adapter as soon as I come back. I might need it for my work anyway.

I think I won't make it to DjangoConEu this year (which makes me really sad) but if I can help anyhow, let me know @nanuxbe !

**Comment by nanuxbe** [comment]
Thanks @adrienbrunet ,

If you get to writing an Vue adapter, I guess it would be great if you could document the process and that could be used as a base for developer documentation, what we have right now is very thin...

The other thing that is mostly missing from the documentation are the new features (more flexible factories, pagination, improved decorators, ...) but I guess that I'm probably the one that should document those since I know what they do and why they were needed.

If you want to take a look at https://github.com/drf-forms/drf-schema-adapter/tree/cookbooks there's already some work that's been done there for different use-cases.

**Comment by larsrinn** [comment]
Also I'll attend this years DjangoConEu and will be happy to assist you in continuing this project.

About Vue: It's true, that Vue doesn't have its own data model. MobX+Axios should work - I'll take a look at that. However, Vue provides `Vuex` - similar to Redux. I think, that auto generated services (or whatever they're called for Vue), should provide bindings to vuex automatically. Up to my understanding, the major drawback of using these centralized stores, is the additional boilerplate you have to write in order to set it up. However, it facilitates managing the data flow in the frontend significantly. Hence, auto-generating this boilerplate would be a huge benefit.

However, my Vue (or general frontend)-skills are lagging far behind the Django ones. Therefore, I think somebody with proficient Vue experience would be needed, in order to specify the requirements of auto-generated code from the frontend-perspective.

**Comment by nanuxbe** [comment]
Sorry for the late reply.
You're more than welcome to help during the sprints.
If you are interested, I've also recently learned that I'll be giving a workshop about this library at DjangoCon Eu, so hopefully, that will give it a bit more visibility

**Comment by nanuxbe** [comment]
Closing this issue as the discussion has died down and it's not an actual issue
