### ISSUE TITLE
make include_str settable

### ISSUE THREAD

**Issue by wingyiu** [drf-forms/drf-schema-adapter#29]
make `include_str` paramable or settable or default false. #

**Comment by nanuxbe** [comment]
`include_str` is already settable. You can set it on each Endpoint individually.

If you want all your endpoints to have `include_str = False`, create your own Enpoint base class like

```
from drf_auto_endpoint.endpoints import Endpoint as BaseEndpoint

class Endpoint(BaseEndpoint):
    include_str = False
```

and have your endpoints inherit from that Endpoint class instead of the one provided by DRF-Schema-Adapter.

I am closing this issue. If this is not what you were asking about, feel free to re-open

**Comment by wingyiu** [comment]
not settable with `register()`
