### ISSUE TITLE
json-schema support

### ISSUE THREAD

**Issue by gthieleb** [drf-forms/drf-schema-adapter#37]
I would like to use alpaca [1] json form created from drf using a [json-schema](http://json-schema.org/). They support most of the json-schema API. Is this project the right starting point for implementing  metadata in json-scheme format?

I like the idea of creating serializer/viewset for models on the fly and struggling using the `drf_auto_endpoint` or  `drf-nested-routers` [2] for this approach. Do you know the second and may explain where both differs?

[1] https://github.com/gitana/alpaca
[2] https://github.com/alanjds/drf-nested-routers

**Comment by gthieleb** [comment]
Hi @nanuxbe thanks for your detailed application. 

I think I am looking a functionality drf-schema-adapter offers. 

Let me describe my requirement shortly:

Currently I already have the prototype of a dynamic form, created by drf static serializer/viewset with a multiple of select fields, where field options dynamically is adapted by using filtersets based on the selection of other select fields.

The filtering is done against a intermediate table that contains the values valid for the select field options.

As we currently have to maintain the serializers / viewsets / filtersets by hand and there are more than 30 serializers involved my idea is to perform the creation of serializers, viewsets, filtersets dynamicly.
I am thinking of creating an api entry (`/api/form1/{data, options}`) where options is the entry for nested routes to intermediate model (`form1/options/{selectfield1, selectfield2, ...}`). `form1/data` is the endpoint for form `CRUD`. 

The foreign key fields where a serializer is neccessary should be autodetected by iterating the form base serializer model and looking for `ForeignKey` fields. The filtering should be based on the `to_field` of the intermediate model. The Filterset should be created dynamically, based on the select fields involved and filtering against the intermediate model without the current field.

Do you think this is a usecase that could be realised on `drf_auto_endpoint`?

Thanks for the hint with base adapter. I will play with it.

**Comment by nanuxbe** [comment]
Hi,
the FilterSet for such format `form1/options/{selectfield1, selectfield2}` is not standard and you won't be able to create those automatically out of the box but you'll be able to create the serializers directly out of the box and you'll also be able to create viewsets, you'll have to specify the `filter_class` manually though.

Your endpoints would look like something like this:

```python
class MyEndpoint(Endpoint):
    model = MyModel
    filter_class = MyFilterSet
```
As far as I remember, json-schema doesn't provide a native solution for specifying foreign-keys but drf-schema-adapter can provide it and instead of building complex `FilterSet`'s I would try to take advantage of the information the MetaClass can provide.
If you go to http://djembersample.pythonanywhere.com and log in you'll have full access to the api at http://djembersample.pythonanywhere.com/api/v1/, browse a bit and click on the `OPTIONS` button to see the kind of data that can be provided by a more complete adapter than the `BaseAdapter` especially regarding relationships like:
```
        {
            "translated": false,
            "label": "Invoices",
            "validations": {},
            "required": false,
            "widget": "tomany-table",
            "extra": {
                "related_model": "accounting/invoice"
            },
            "readonly": false,
            "name": "invoices"
        }, {
            "translated": false,
            "label": "Default Contact",
            "validations": {},
            "required": false,
            "widget": "foreignkey",
            "extra": {
                "related_model": "crm/contact"
            },
            "readonly": false,
            "name": "default_contact"
        },
```

**Comment by gthieleb** [comment]
Hi @nanuxbe
 
thanks for your detailed answer. It sound for me like we are in the same direction. 

Sorry my misexplanation. Of course the Filterset won't be done with `/form1/options/selectfield1` but 
with `/form1/options/selectfield1?selectfield1=A&selectfield2=X&selectfield3=N`. Where `A`, `X` and `N` are choices made in the form. 

A Filterset class for a formfield options class should consist of the ForeignKey model class and filter definitions that translate the selectfield to the reverse fields of the intermediate model class.
e.g. the FilterSet class for selectfield1 would look like:

```
class SelectField1FilterSet(FilterSet):
    selectfield2 = filters.CharFilter(name='intermediatemodel__selectfield2')
    selectfield3 = filters.CharFilter(name='intermediatemodel__selectfield3')
    
    class Meta: 
        model = SelectField1
        fields = ('selectfield2',
                  'selectfield3')
```

Of course `selectfield1` in the query above is not neccessary and is silently dropped by this FilterSet. 

Is this similar to what `related_model` does?

**Comment by nanuxbe** [comment]
This is in some ways similar to `related_model`.

`related_model` is used to tell the model which endpoint to query to get the list of models (filtered or not).
As far as I'm aware though it is not a "standard" feature of son-schema therefore there will most likely be some extra work to do on the frontend as well.

**Comment by gthieleb** [comment]
Yes thats true. There is the responsibility of the form to retrieve the values for option fields on itself.
Some must implement some javascript code around that. 
With alpaca this is already done within the datasource capability [1]. You only need to put the correct url (generated endpoint route + query params) as datasource to the appropriate fieldset(s) and enable (re)loading via "onSelect" event. I wonder if this is easier to realise with Ember btw. 

[1] http://www.alpacajs.org/docs/api/datasources.html

**Comment by nanuxbe** [comment]
Easier is a relative term but yes Ember (with ember-cli-crudities) will makes things more flexible mostly because it has a data layer to talk to api's (ember-data) the same way Django has an ORM. But the principle of datasource is indeed the same.

It might be a personal bias, I just have the feeling that Ember with its data layer can make things more flexible. Like leveraging relationships on the frontend.
Like if you want to create a form for an `Invoice`, the invoice has a `Party` (foreign key) and for that invoice you need an active billing address of the party. You can achieve it like that:
```
{
  "name": "address",
  "required": false,
  "widget": "foreignkey",
  "label": "Address",
  "extra": {
    "related_model": "crm/address",
    "property_path": "party.addresses",
    "query": {
      "is_active": true,
      "is_billing": true
    },
  },
}
```
Since Ember is aware of data relationships it knows about the foreign key between invoice and party as well as the one-to-many relationship between party and address.
You could of course achieve the same result with Alpaca just you would have to do it "outside" of your database structure (I'm not sure I'm being very clear here)

In the long-term, Ember makes it easier to keep a more structured code-base. You can can keep a jQuery code-base structured as well, it ust doesn't come as easily

**Comment by nanuxbe** [comment]
I believe this discussion thread is finish therefore I'm closing this issue. If you have anything to add, feel-free to re-open
